/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classmanagmentsystem;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sewmi
 */
public class Add_Subject extends javax.swing.JFrame {
     JDBC jdbc=new JDBC();
    private static String  subid;
    /**
     * Creates new form Add_Subject
     */
    public Add_Subject() {
        initComponents();
         genNewSubID();
        btnUpdate.setVisible(false);
    }
    public Add_Subject(String sub){
        initComponents();
        subid=sub;
        loadSubjectDetails(subid);
        btnAdd.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsubid = new javax.swing.JTextField();
        txtsubname = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/icons8_System_Information_48px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Add Subject");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 20, -1, -1));

        jLabel3.setText("Subject Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel4.setText("Subject Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        txtsubid.setEditable(false);
        getContentPane().add(txtsubid, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 73, 105, -1));
        getContentPane().add(txtsubname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 113, 151, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 80, 40));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Save");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String subId=txtsubid.getText();
       String subject=txtsubname.getText();
        jdbc.putData("INSERT INTO subject_details(SubjectID,SubjectName)VALUES('"+subId+"','"+subject+"')");
        JOptionPane.showMessageDialog(null, "Student added successfully");
    }//GEN-LAST:event_btnAddActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
      txtsubid.setText("");
      txtsubname.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         String sid=txtsubid.getText();
       String name=txtsubname.getText();
       jdbc.putData("UPDATE subject_details SET SubjectID='"+sid+"',SubjectName='"+name+"' WHERE SubjectID='"+sid+"')");
        JOptionPane.showMessageDialog(null, "Saved your details successfully");
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtsubid;
    private javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables

    private void genNewSubID() {
        try {
            ResultSet rs=new JDBC().getData("SELECT MAX(SubjectID) FROM SubjectName");
            rs.next();
            int id=Integer.valueOf(rs.getString("MAX(SubjectName)"))+1;
            txtsubid.setText(String.valueOf(id));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSubjectDetails(String subid) {
        JDBC jdbc=new JDBC();
        try {
            ResultSet rs=jdbc.getData("SELECT SubjectID,SubjectName FROM subject_details where SubjectID= '"+subid+"'");
            if(rs.next()){
                txtsubid.setText(rs.getString("SubjectID"));
                txtsubname.setText(rs.getString("SubjectName"));

            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
      jdbc.close();
    }
}
